#!/usr/bin/env python3
"""
Test script to validate GitHub fine-grained token permissions for file commits
"""

import os
import base64
from github import Github
from dotenv import load_dotenv

def test_github_commit():
    """Test GitHub commit functionality with current token"""
    
    load_dotenv()
    token = os.getenv('GITHUB_TOKEN')
    
    if not token:
        print("❌ No GitHub token found in .env file")
        return False
    
    try:
        print("🔧 Testing GitHub API access...")
        
        # Initialize GitHub client
        g = Github(token)
        user = g.get_user()
        print(f"✅ Authenticated as: {user.login}")
        
        # Access repository
        repo_name = "jenilChristo/AgenticAI_Autonomous-ETL-Agent"
        repo = g.get_repo(repo_name)
        print(f"✅ Repository accessed: {repo.name}")
        print(f"🔒 Permissions: {repo.permissions}")
        
        # Test content - simple test file
        test_content = """# Test Notebook Generated by Autonomous ETL Agent

This is a test notebook to validate GitHub commit functionality.

## Test Information
- Generated by: Autonomous ETL Agent System  
- Target Branch: aiagent
- Test Purpose: Validate fine-grained GitHub token permissions

## Status
✅ Commit successful if you can see this file!
"""
        
        # Encode content to base64
        content_bytes = test_content.encode('utf-8')
        content_b64 = base64.b64encode(content_bytes).decode('utf-8')
        
        # Test file path
        test_file_path = "test_files/github_commit_test.md"
        
        print(f"📝 Testing commit to path: {test_file_path}")
        print(f"📄 Content length: {len(test_content)} characters")
        
        # Try to create the file
        try:
            # Check if file exists
            try:
                existing_file = repo.get_contents(test_file_path, ref="aiagent")
                print("🔄 File exists, updating...")
                result = repo.update_file(
                    path=test_file_path,
                    message="Test commit: Update GitHub integration test file",
                    content=test_content,
                    sha=existing_file.sha,
                    branch="aiagent"
                )
            except:
                print("➕ Creating new file...")
                result = repo.create_file(
                    path=test_file_path,
                    message="Test commit: Add GitHub integration test file",
                    content=test_content,
                    branch="aiagent"
                )
            
            print(f"✅ SUCCESS: File committed!")
            print(f"📂 Commit SHA: {result['commit'].sha}")
            print(f"🔗 Commit URL: {result['commit'].html_url}")
            
            return True
            
        except Exception as commit_error:
            print(f"❌ COMMIT FAILED: {commit_error}")
            
            # Check specific error details
            if "403" in str(commit_error):
                print("\n🔍 PERMISSION ANALYSIS:")
                print("Fine-grained GitHub tokens need specific permissions:")
                print("1. Contents: Read and write")
                print("2. Metadata: Read")  
                print("3. Pull requests: Write (if creating PRs)")
                print("\nTo fix this:")
                print("1. Go to https://github.com/settings/tokens")
                print("2. Click on your fine-grained token")
                print("3. Under 'Repository permissions', ensure:")
                print("   - Contents: Read and write")
                print("   - Metadata: Read")
                print("   - Pull requests: Write")
                print("4. Save the changes")
                
            return False
    
    except Exception as e:
        print(f"❌ GitHub API error: {e}")
        return False

if __name__ == "__main__":
    print("🧪 TESTING GITHUB COMMIT FUNCTIONALITY")
    print("=" * 50)
    success = test_github_commit()
    
    if success:
        print("\n🎉 SUCCESS: GitHub integration is working!")
        print("The end-to-end pipeline should now work correctly.")
    else:
        print("\n💡 NEXT STEPS:")
        print("1. Update your fine-grained token permissions")
        print("2. Re-run this test to verify")
        print("3. Then test the full end-to-end pipeline")